import 'package:slate_render/slate.dart';

List<Content> contentList = [
  Content(
    type: "paragraph",
    children: [
      ChildContent(
        bold: true,
        text: "This is the children text 1",
        italic: true,
        underline: true,
        closeText: false,
        children: [
          ChildContent(
            bold: true,
            text: "This is the children text 11",
            italic: true,
            underline: true,
            closeText: false,
            type: "paragraph",
            url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
            color: "#4287f5",
            bgColor: "",
          ),
        ],
        type: "paragraph",
        url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
        color: "#f54e42",
        bgColor: "",
      ),
      ChildContent(
        bold: true,
        text: "This is the children text 2",
        italic: true,
        underline: true,
        closeText: false,
        type: "paragraph",
        url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
        color: "#f57842",
        bgColor: "",
      ),
      ChildContent(
        bold: true,
        text: "This is the children text 3",
        italic: true,
        underline: true,
        closeText: false,
        type: "paragraph",
        url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
        color: "#f57842",
        bgColor: "",
      ),
    ],
    url: "http://www.google.com",
    width: 1,
    anchor: "",
    height: 1,
    alignment: "left",
    redirection: false,
  ),
  Content(
    type: "heading-1",
    children: [
      ChildContent(
        bold: true,
        text: "This is the children text 1",
        italic: true,
        underline: true,
        closeText: false,
        children: [
          ChildContent(
            bold: true,
            text: "This is the children text 11",
            italic: true,
            underline: true,
            closeText: false,
            type: "heading-1",
            url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
            color: "#4287f5",
            bgColor: "",
          ),
        ],
        type: "paragraph",
        url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
        color: "#f54e42",
        bgColor: "",
      ),
      ChildContent(
        bold: true,
        text: "This is the children text 2",
        italic: true,
        underline: true,
        closeText: false,
        type: "paragraph",
        url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
        color: "#f57842",
        bgColor: "",
      ),
      ChildContent(
        bold: true,
        text: "This is the children text 3",
        italic: true,
        underline: true,
        closeText: false,
        type: "paragraph",
        url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
        color: "#f57842",
        bgColor: "",
      ),
    ],
    url: "http://www.google.com",
    width: 1,
    anchor: "",
    height: 1,
    alignment: "left",
    redirection: false,
  ),
  Content(
    type: "heading-2",
    children: [
      ChildContent(
        bold: true,
        text: "This is the children text 1",
        italic: true,
        underline: true,
        closeText: false,
        children: [
          ChildContent(
            bold: true,
            text: "This is the children text 11",
            italic: true,
            underline: true,
            closeText: false,
            type: "paragraph",
            url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
            color: "#4287f5",
            bgColor: "",
          ),
        ],
        type: "paragraph",
        url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
        color: "#f54e42",
        bgColor: "",
      ),
      ChildContent(
        bold: true,
        text: "This is the children text 2",
        italic: true,
        underline: true,
        closeText: false,
        type: "paragraph",
        url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
        color: "#f57842",
        bgColor: "",
      ),
      ChildContent(
        bold: true,
        text: "This is the children text 3",
        italic: true,
        underline: true,
        closeText: false,
        type: "paragraph",
        url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
        color: "#f57842",
        bgColor: "",
      ),
    ],
    url: "http://www.google.com",
    width: 1,
    anchor: "",
    height: 1,
    alignment: "left",
    redirection: false,
  ),
  Content(
    type: "heading-3",
    children: [
      ChildContent(
        bold: true,
        text: "This is the children text 1",
        italic: true,
        underline: true,
        closeText: false,
        children: [
          ChildContent(
            bold: true,
            text: "This is the children text 11",
            italic: true,
            underline: true,
            closeText: false,
            type: "paragraph",
            url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
            color: "#4287f5",
            bgColor: "",
          ),
        ],
        type: "paragraph",
        url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
        color: "#f54e42",
        bgColor: "",
      ),
      ChildContent(
        bold: true,
        text: "This is the children text 2",
        italic: true,
        underline: true,
        closeText: false,
        type: "paragraph",
        url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
        color: "#f57842",
        bgColor: "",
      ),
      ChildContent(
        bold: true,
        text: "This is the children text 3",
        italic: true,
        underline: true,
        closeText: false,
        type: "paragraph",
        url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
        color: "#f57842",
        bgColor: "",
      ),
    ],
    url: "http://www.google.com",
    width: 1,
    anchor: "",
    height: 1,
    alignment: "left",
    redirection: false,
  ),
  Content(
    type: "numbered-list",
    children: [
      ChildContent(
        bold: true,
        text: "This is the children text 1",
        italic: true,
        underline: true,
        closeText: false,
        children: [
          ChildContent(
            bold: true,
            text: "This is the children text 11",
            italic: true,
            underline: true,
            closeText: false,
            type: "paragraph",
            url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
            color: "#4287f5",
            bgColor: "",
          ),
          ChildContent(
            bold: true,
            text: "This is the children text 11",
            italic: true,
            underline: true,
            closeText: false,
            type: "image",
            url:
                "https://edisonlms-fs-staging.s3.ap-south-1.amazonaws.com/tenant_neeraj/72b784b3-0426-4e42-a0e2-731b0c20dc20_1679373965173_Untitled.png",
            color: "#4287f5",
            bgColor: "",
          ),
        ],
        type: "paragraph",
        url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
        color: "#f54e42",
        bgColor: "",
      ),
      ChildContent(
        bold: true,
        text: "This is the children text 2",
        italic: true,
        underline: true,
        closeText: false,
        type: "paragraph",
        url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
        color: "#f57842",
        bgColor: "",
      ),
      ChildContent(
        bold: true,
        text: "This is the children text 3",
        italic: true,
        underline: true,
        closeText: false,
        type: "paragraph",
        url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
        color: "#f57842",
        bgColor: "",
      ),
    ],
    url: "http://www.google.com",
    width: 1,
    anchor: "",
    height: 1,
    alignment: "left",
    redirection: false,
  ),
  Content(
    type: "bulleted-list",
    children: [
      ChildContent(
        bold: true,
        text: "This is the children text 1",
        italic: true,
        underline: true,
        closeText: false,
        children: [
          ChildContent(
            bold: true,
            text: "This is the children text 11",
            italic: true,
            underline: true,
            closeText: false,
            type: "paragraph",
            url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
            color: "#4287f5",
            bgColor: "",
          ),
        ],
        type: "paragraph",
        url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
        color: "#f54e42",
        bgColor: "",
      ),
      ChildContent(
        bold: true,
        text: "This is the children text 2",
        italic: true,
        underline: true,
        closeText: false,
        type: "paragraph",
        url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
        color: "#f57842",
        bgColor: "",
      ),
      ChildContent(
        bold: true,
        text: "This is the children text 3",
        italic: true,
        underline: true,
        closeText: false,
        type: "paragraph",
        url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
        color: "#f57842",
        bgColor: "",
      ),
    ],
    url: "http://www.google.com",
    width: 1,
    anchor: "",
    height: 1,
    alignment: "left",
    redirection: false,
  ),
  Content(
    type: "list-item",
    children: [
      ChildContent(
        bold: true,
        text: "This is the children text 1",
        italic: true,
        underline: true,
        closeText: false,
        children: [
          ChildContent(
            bold: true,
            text: "This is the children text 11",
            italic: true,
            underline: true,
            closeText: false,
            type: "paragraph",
            url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
            color: "#4287f5",
            bgColor: "",
          ),
        ],
        type: "paragraph",
        url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
        color: "#f54e42",
        bgColor: "",
      ),
      ChildContent(
        bold: true,
        text: "This is the children text 2",
        italic: true,
        underline: true,
        closeText: false,
        type: "paragraph",
        url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
        color: "#f57842",
        bgColor: "",
      ),
      ChildContent(
        bold: true,
        text: "This is the children text 3",
        italic: true,
        underline: true,
        closeText: false,
        type: "paragraph",
        url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
        color: "#f57842",
        bgColor: "",
      ),
    ],
    url: "http://www.google.com",
    width: 1,
    anchor: "",
    height: 1,
    alignment: "left",
    redirection: false,
  ),
  Content(
    type: "image",
    children: [
      ChildContent(
        bold: true,
        text: "This is the children text 1",
        italic: true,
        underline: true,
        closeText: false,
        children: [
          ChildContent(
            bold: true,
            text: "This is the children text 11",
            italic: true,
            underline: true,
            closeText: false,
            type: "paragraph",
            url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
            color: "#4287f5",
            bgColor: "",
          ),
        ],
        type: "paragraph",
        url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
        color: "#f54e42",
        bgColor: "",
      ),
      ChildContent(
        bold: true,
        text: "This is the children text 2",
        italic: true,
        underline: true,
        closeText: false,
        type: "paragraph",
        url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
        color: "#f57842",
        bgColor: "",
      ),
      ChildContent(
        bold: true,
        text: "This is the children text 3",
        italic: true,
        underline: true,
        closeText: false,
        type: "paragraph",
        url: "https://support.apple.com/en-in/guide/mac-help/mchlp2265/mac",
        color: "#f57842",
        bgColor: "",
      ),
    ],
    url: "http://www.google.com",
    width: 1,
    anchor: "",
    height: 1,
    alignment: "left",
    redirection: false,
  ),
];
