// create a dummay data with single object which contains all the necessary combinaltion for example
// paragraph, heading, list(un ,or), link, image
List<Map<String, dynamic>> mapList = [
  {
    "type": "paragraph",
    "children": [
      {
        "bold": true,
        "text": "This is the children text 1",
        "italic": true,
        "underline": true,
        "closeText": false,
        "children": [
          {
            "bold": true,
            "text": "This is the children text 11",
            "italic": true,
            "underline": true,
            "closeText": false,
            "type": "paragraph",
            "url": "https://pub.dev/",
            "color": "#4287f5",
            "bgColor": "",
          },
        ],
        "type": "paragraph",
        "url": "https://pub.dev/",
        "color": "#f54e42",
        "bgColor": "",
      },
      {
        "bold": true,
        "text": "This is the children text 2",
        "italic": true,
        "underline": true,
        "closeText": false,
        "type": "paragraph",
        "url": "https://pub.dev/",
        "color": "#f57842",
        "bgColor": "",
      },
      {
        "bold": true,
        "text": "This is the children text 3",
        "italic": true,
        "underline": true,
        "closeText": false,
        "type": "paragraph",
        "url": "https://pub.dev/",
        "color": "#f57842",
        "bgColor": "",
      },
    ],
    "url": "http://www.google.com",
    "width": 1,
    "anchor": "",
    "height": 1,
    "alignment": "left",
    "redirection": false,
  },
  {
    "type": "heading-1",
    "children": [
      {
        "bold": true,
        "text": "This is the children text 1",
        "italic": true,
        "underline": true,
        "closeText": false,
        "children": [
          {
            "bold": true,
            "text": "This is the children text 11",
            "italic": true,
            "underline": true,
            "closeText": false,
            "type": "heading-1",
            "url": "https://pub.dev/",
            "color": "#4287f5",
            "bgColor": "",
          },
        ],
        "type": "paragraph",
        "url": "https://pub.dev/",
        "color": "#f54e42",
        "bgColor": "",
      },
      {
        "bold": true,
        "text": "This is the children text 2",
        "italic": true,
        "underline": true,
        "closeText": false,
        "type": "paragraph",
        "url": "https://pub.dev/",
        "color": "#f57842",
        "bgColor": "",
      },
      {
        "bold": true,
        "text": "This is the children text 3",
        "italic": true,
        "underline": true,
        "closeText": false,
        "type": "paragraph",
        "url": "https://pub.dev/",
        "color": "#f57842",
        "bgColor": "",
      },
    ],
    "url": "http://www.google.com",
    "width": 1,
    "anchor": "",
    "height": 1,
    "alignment": "left",
    "redirection": false,
  },
  {
    "type": "heading-2",
    "children": [
      {
        "bold": true,
        "text": "This is the children text 1",
        "italic": true,
        "underline": true,
        "closeText": false,
        "children": [
          {
            "bold": true,
            "text": "This is the children text 11",
            "italic": true,
            "underline": true,
            "closeText": false,
            "type": "heading-1",
            "url": "https://pub.dev/",
            "color": "#4287f5",
            "bgColor": "",
          },
        ],
        "type": "paragraph",
        "url": "https://pub.dev/",
        "color": "#f54e42",
        "bgColor": "",
      },
      {
        "bold": true,
        "text": "This is the children text 2",
        "italic": true,
        "underline": true,
        "closeText": false,
        "type": "paragraph",
        "url": "https://pub.dev/",
        "color": "#f57842",
        "bgColor": "",
      },
      {
        "bold": true,
        "text": "This is the children text 3",
        "italic": true,
        "underline": true,
        "closeText": false,
        "type": "paragraph",
        "url": "https://pub.dev/",
        "color": "#f57842",
        "bgColor": "",
      },
    ],
    "url": "http://www.google.com",
    "width": 1,
    "anchor": "",
    "height": 1,
    "alignment": "left",
    "redirection": false,
  },
  {
    "type": "heading-3",
    "children": [
      {
        "bold": true,
        "text": "This is the children text 1",
        "italic": true,
        "underline": true,
        "closeText": false,
        "children": [
          {
            "bold": true,
            "text": "This is the children text 11",
            "italic": true,
            "underline": true,
            "closeText": false,
            "type": "heading-1",
            "url": "https://pub.dev/",
            "color": "#4287f5",
            "bgColor": "",
          },
        ],
        "type": "paragraph",
        "url": "https://pub.dev/",
        "color": "#f54e42",
        "bgColor": "",
      },
      {
        "bold": true,
        "text": "This is the children text 2",
        "italic": true,
        "underline": true,
        "closeText": false,
        "type": "paragraph",
        "url": "https://pub.dev/",
        "color": "#f57842",
        "bgColor": "",
      },
      {
        "bold": true,
        "text": "This is the children text 3",
        "italic": true,
        "underline": true,
        "closeText": false,
        "type": "paragraph",
        "url": "https://pub.dev/",
        "color": "#f57842",
        "bgColor": "",
      },
    ],
    "url": "http://www.google.com",
    "width": 1,
    "anchor": "",
    "height": 1,
    "alignment": "left",
    "redirection": false,
  },
  {
    "type": "numbered-list",
    "children": [
      {
        "bold": true,
        "text": "This is the children text 1",
        "italic": true,
        "underline": true,
        "closeText": false,
        "children": [
          {
            "bold": true,
            "text": "This is the children text 11",
            "italic": true,
            "underline": true,
            "closeText": false,
            "type": "paragraph",
            "url": "https://pub.dev/",
            "color": "#4287f5",
            "bgColor": "",
          },
          {
            "bold": true,
            "text": "This is the children text 11",
            "italic": true,
            "underline": true,
            "closeText": false,
            "type": "image",
            "url":
                "https://images.unsplash.com/photo-1755930523772-79e4443c9e4a?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            "color": "#4287f5",
            "bgColor": "",
          },
        ],
        "type": "paragraph",
        "url": "https://pub.dev/",
        "color": "#f54e42",
        "bgColor": "",
      },
      {
        "bold": true,
        "text": "This is the children text 2",
        "italic": true,
        "underline": true,
        "closeText": false,
        "type": "paragraph",
        "url": "https://pub.dev/",
        "color": "#f57842",
        "bgColor": "",
      },
      {
        "bold": true,
        "text": "This is the children text 3",
        "italic": true,
        "underline": true,
        "closeText": false,
        "type": "paragraph",
        "url": "https://pub.dev/",
        "color": "#f57842",
        "bgColor": "",
      },
    ],
    "url": "http://www.google.com",
    "width": 1,
    "anchor": "",
    "height": 1,
    "alignment": "left",
    "redirection": false,
  },
  {
    "type": "bulleted-list",
    "children": [
      {
        "bold": true,
        "text": "This is the children text 1",
        "italic": true,
        "underline": true,
        "closeText": false,
        "children": [
          {
            "bold": true,
            "text": "This is the children text 11",
            "italic": true,
            "underline": true,
            "closeText": false,
            "type": "paragraph",
            "url": "https://pub.dev/",
            "color": "#4287f5",
            "bgColor": "",
          },
        ],
        "type": "paragraph",
        "url": "https://pub.dev/",
        "color": "#f54e42",
        "bgColor": "",
      },
      {
        "bold": true,
        "text": "This is the children text 2",
        "italic": true,
        "underline": true,
        "closeText": false,
        "type": "paragraph",
        "url": "https://pub.dev/",
        "color": "#f57842",
        "bgColor": "",
      },
      {
        "bold": true,
        "text": "This is the children text 3",
        "italic": true,
        "underline": true,
        "closeText": false,
        "type": "paragraph",
        "url": "https://pub.dev/",
        "color": "#f57842",
        "bgColor": "",
      },
    ],
    "url": "http://www.google.com",
    "width": 1,
    "anchor": "",
    "height": 1,
    "alignment": "left",
    "redirection": false,
  },
  {
    "type": "list-item",
    "children": [
      {
        "bold": true,
        "text": "This is the children text 1",
        "italic": true,
        "underline": true,
        "closeText": false,
        "children": [
          {
            "bold": true,
            "text": "This is the children text 11",
            "italic": true,
            "underline": true,
            "closeText": false,
            "type": "paragraph",
            "url": "https://pub.dev/",
            "color": "#4287f5",
            "bgColor": "",
          },
        ],
        "type": "paragraph",
        "url": "https://pub.dev/",
        "color": "#f54e42",
        "bgColor": "",
      },
      {
        "bold": true,
        "text": "This is the children text 2",
        "italic": true,
        "underline": true,
        "closeText": false,
        "type": "paragraph",
        "url": "https://pub.dev/",
        "color": "#f57842",
        "bgColor": "",
      },
      {
        "bold": true,
        "text": "This is the children text 3",
        "italic": true,
        "underline": true,
        "closeText": false,
        "type": "paragraph",
        "url": "https://pub.dev/",
        "color": "#f57842",
        "bgColor": "",
      },
    ],
    "url": "http://www.google.com",
    "width": 1,
    "anchor": "",
    "height": 1,
    "alignment": "left",
    "redirection": false,
  },
  {
    "type": "image",
    "children": [
      {
        "bold": true,
        "text": "This is the children text 1",
        "italic": true,
        "underline": true,
        "closeText": false,
        "children": [
          {
            "bold": true,
            "text": "This is the children text 11",
            "italic": true,
            "underline": true,
            "closeText": false,
            "type": "paragraph",
            "url": "https://pub.dev/",
            "color": "#4287f5",
            "bgColor": "",
          },
        ],
        "type": "paragraph",
        "url": "https://pub.dev/",
        "color": "#f54e42",
        "bgColor": "",
      },
      {
        "bold": true,
        "text": "This is the children text 2",
        "italic": true,
        "underline": true,
        "closeText": false,
        "type": "paragraph",
        "url": "https://pub.dev/",
        "color": "#f57842",
        "bgColor": "",
      },
      {
        "bold": true,
        "text": "This is the children text 3",
        "italic": true,
        "underline": true,
        "closeText": false,
        "type": "paragraph",
        "url": "https://pub.dev/",
        "color": "#f57842",
        "bgColor": "",
      },
    ],
    "url": "http://www.google.com",
    "width": 1,
    "anchor": "",
    "height": 1,
    "alignment": "left",
    "redirection": false,
  },
];
