name: slate_render
description: "A Flutter package to parse and render Slate Editor JSON into rich Flutter widgets."
version: 0.0.1
homepage: https://github.com/FarmanWork/slate_render
repository: https://github.com/FarmanWork/slate_render
issue_tracker: https://github.com/FarmanWork/slate_render/issues
documentation: https://github.com/FarmanWork/slate_render?tab=readme-ov-file#slate_render

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.0
  json_serializable: ^6.10.0
  freezed: ^3.2.0

screenshots:
  - description: 'Home View.'
    path: screenshot_home.png
  - description: 'Single Item View'
    path: screenshot_view.png
  - description: 'Image view'
    path: screenshot_image_view.png

topics:
  - slateditor
  - editor    